# Generated by Django 4.1 on 2022-08-05 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libreria", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="libro",
            options={"ordering": ["title", "editorial"]},
        ),
        migrations.AddField(
            model_name="libro",
            name="editorial",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Editorial"
            ),
        ),
        migrations.AddField(
            model_name="libro",
            name="isbn",
            field=models.CharField(
                blank=True, max_length=13, null=True, verbose_name="ISBN"
            ),
        ),
        migrations.AlterField(
            model_name="libro",
            name="title",
            field=models.CharField(max_length=50, verbose_name="Título"),
        ),
    ]
