# Generated by Django 4.1 on 2022-08-05 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libreria", "0002_alter_libro_options_libro_editorial_libro_isbn_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Autor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Nombre"
                    ),
                ),
                ("last_name", models.CharField(max_length=50, verbose_name="Apellido")),
            ],
            options={
                "ordering": ["last_name", "name"],
            },
        ),
        migrations.CreateModel(
            name="Genero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Ingresa un género de libro (ej. Ciencia Ficción, Misterio",
                        max_length=100,
                        verbose_name="Género",
                    ),
                ),
            ],
        ),
    ]
