# Generated by Django 4.1 on 2022-08-05 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("libreria", "0003_autor_genero"),
    ]

    operations = [
        migrations.CreateModel(
            name="Idioma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idioma", models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name="autor",
            options={
                "ordering": ["last_name", "name"],
                "verbose_name_plural": "Autores",
            },
        ),
        migrations.AlterField(
            model_name="genero",
            name="name",
            field=models.CharField(
                help_text="Ingresa un género de libro (ej. Ciencia Ficción, Misterio)",
                max_length=100,
                verbose_name="Género",
            ),
        ),
        migrations.AddField(
            model_name="libro",
            name="idioma",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="libreria.idioma",
            ),
        ),
    ]
