# Generated by Django 4.1 on 2022-08-05 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("libreria", "0004_idioma_alter_autor_options_alter_genero_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="libro",
            name="autor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="libreria.autor",
                verbose_name="Autor",
            ),
        ),
        migrations.AddField(
            model_name="libro",
            name="genero",
            field=models.ManyToManyField(to="libreria.genero", verbose_name="Género"),
        ),
    ]
