# Generated by Django 4.1 on 2022-08-05 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libreria", "0005_libro_autor_libro_genero"),
    ]

    operations = [
        migrations.AddField(
            model_name="libro",
            name="resumen",
            field=models.TextField(
                blank=True, max_length=1000, null=True, verbose_name="Resumen"
            ),
        ),
    ]
