# Generated by Django 4.1 on 2022-08-05 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libreria", "0007_libro_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="libro",
            name="price",
            field=models.FloatField(verbose_name="Precio"),
        ),
    ]
