# Generated by Django 4.1 on 2022-08-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libreria", "0009_autor_nacionalidad"),
    ]

    operations = [
        migrations.AlterField(
            model_name="autor",
            name="nacionalidad",
            field=models.CharField(
                blank=True,
                help_text="País de origen",
                max_length=50,
                null=True,
                verbose_name="Nacionalidad",
            ),
        ),
    ]
