# Generated by Django 4.1 on 2022-08-07 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("libreria", "0010_alter_autor_nacionalidad"),
    ]

    operations = [
        migrations.AlterField(
            model_name="libro",
            name="resumen",
            field=models.TextField(
                blank=True, max_length=1000, null=True, verbose_name="Reseña"
            ),
        ),
    ]
